### ISSUE TITLE
problem running example

### ISSUE THREAD

**Issue by fipoucat** [AleksandarSekulic/RFSI#3]
Hi,

I found your interesting package and installed it. While trying to run the example I am having an error:
[1] "Preparing data ..."
Error in data.prepare(data = data, data.staid.x.y.z = data.staid.x.y.z,  : 
  The argument data/newdata must be of sf, sftime, SpatVector, SpatRaster (as newdata only), data.frame class!
What's the cause and what to do?

**Comment by AleksandarSekulic** [comment]
Hi,

Can you send me a code example?
As it says, the data must be of sf, sftime, SpatVector, SpatRaster (as newdata only), data.frame class! I suppose that the data or newdata is not in one of these formats.
Check an [example](https://github.com/AleksandarSekulic/Rmeteo/blob/master/demo/RFSI.R) from R [meteo](https://github.com/AleksandarSekulic/Rmeteo/tree/master) package.

**Comment by fipoucat** [comment]
This code:

library(meteo)
library(sp)
library(spacetime)
library(gstat)
library(plyr)
library(xts)
library(snowfall)
library(doParallel)
library(CAST)
library(ranger)
library(sf)
# preparing data
demo(meuse, echo=FALSE)
meuse <- meuse[complete.cases(meuse@data),]

#################### rfsi ####################

fm.RFSI <- as.formula("zinc ~ dist + soil + ffreq")

rfsi_model <- rfsi(formula = fm.RFSI,
                   data = meuse,
                   zero.tol = 0,
                   n.obs = 5, # number of nearest observations
                   s.crs = NA, # or meuse@proj4string # nedded only if in lon/lat (WGS84)
                   t.crs = NA, # or meuse@proj4string # nedded only if in lon/lat (WGS84)
                   cpus = detectCores()-1,
                   progress = TRUE,
                   # ranger parameters
                   importance = "impurity",
                   seed = 42,
                   num.trees = 250,
                   mtry = 5,
                   splitrule = "variance",
                   min.node.size = 5,
                   sample.fraction = 0.95,
                   quantreg = FALSE)
rfsi_model

# Note that OOB error statistics are biased and should not be considered as accuracy metrics
# (they do not show spatial accuracy)!
# The proper way to assess accuaracy of the RFSI model is by using the nested k-fold
# cross-validation (cv.rfsi function)

sort(rfsi_model$variable.importance)

#################### pred.rfsi ####################

rfsi_prediction <- pred.rfsi(model = rfsi_model,
                             data = meuse, # meuse.df (use data.staid.x.y.time)
                             zcol = "zinc",
                             newdata = meuse.grid, # meuse.grid.df (use newdata.staid.x.y.time)
                             output.format = "SpatialPixelsDataFrame",
                             zero.tol = 0,
                             s.crs = meuse@proj4string, # NA
                             newdata.s.crs = meuse@proj4string, # NA
                             t.crs = meuse@proj4string, # NA
                             cpus = detectCores()-1,
                             progress = TRUE
)

spplot(rfsi_prediction['pred'])

**Comment by AleksandarSekulic** [comment]
The code haven't been updated to new version of R [meteo](https://github.com/AleksandarSekulic/Rmeteo/tree/master) package. It's updated now.
You can find all examples [here](https://github.com/AleksandarSekulic/Rmeteo/blob/master/demo/RFSI.R).
Thank you for noticing this.
